language: c

compiler:
  - gcc
  
before_script:
  - git clone https://github.com/corehacker/ch-pal.git
  - cd ch-pal && autoreconf --install && ./configure && make && sudo make install && cd ..

script: |
  autoreconf --install
  ./configure
  make
  
notifications:
  email:
    - 123sandy@gmail.com
